# Generated by Django 5.2.1 on 2025-05-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_deteccion', models.CharField(max_length=100)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='alertas/')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.camera')),
            ],
        ),
    ]
