# Generated by Django 5.2.1 on 2025-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='certeza_minima',
            field=models.FloatField(default=0.5, help_text='Certeza mínima para detecciones (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='intervalo_captura',
            field=models.FloatField(default=1.0, help_text='Intervalo en segundos entre capturas'),
        ),
    ]
